### PR TITLE
markers: fix a bug when parsing expressions with commas present in value

### LINKED ISSUE #99: Splitting marker expressions by comma has issues with XValidation rules
XValidation rules can contain `,` as a valid part of their value.

For example, `self.all(a, a > 0)` would be a valid rule for checking a list of integers are all greater than 0.

When we split the expression here, the rule value becomes `self.all(a` which is not expected.

We need to adjust the logic to preserve the rule string (and any other value that may include a comma) so that we only add expressions for comma separated strings that also contain an `=` character before the next comma.

CC @everettraven

### PR DESCRIPTION
**Pull request by everettraven**
Fixes #99 

Instead of splitting on solely the `,` character, we now do some more robust normalization for parsing of markers to handle the scenarios where a marker may specify an expression with attributes the have a `,` in their value.

### CODE REVIEW

File: pkg/analysis/helpers/markers/analyzer.go [hunk 1]
```diff
@@ -232,14 +232,32 @@ func extractKnownMarkerIDAndExpressions(id string, marker string) (string, map[s
...
+	expressions = strings.ReplaceAll(expressions, `",`, `',`)
+	expressions = strings.ReplaceAll(expressions, `\"`, `"`)
+	// if the last character of the expression is a double quote, set it to a single quote.
+	// this handles the scenario of something like:
+	// +kubebuilder:validation:XValidation:rule="self.map(a, a == \"foo\")",message="no foo found!"
+	// normalizing it to:
+	// +kubebuilder:validation:XValidation:rule='self.map(a, a == "foo")',message='no foo found!'
+	if expressions[len(expressions)-1] == '"' {
+		expressions = expressions[:len(expressions)-1] + "'"
+	}
```
Comment (everettraven) [inline pkg/analysis/helpers/markers/analyzer.go:255]: This seems to be triggering some issues with other markers - I'll need to come up with something else to handle this scenario and not impact other edge cases.

Comment (yongruilin) [reply pkg/analysis/helpers/markers/analyzer.go:255]: I feel it is too crisp to replace them all. How about parsing the string sequentially? something like https://github.com/kubernetes/gengo/blob/master/v2/codetags/parser.go#L145 we don't need to do it that complicated as I don't expect we need to handle nested tags here, but it is more reliable to parse it sequentially.

**Comment by JoelSpeed** [comment]
/approve
/lgtm

Thanks, this looks like it's going to work way better!
